version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Porta local 3000 acessará o NGINX na porta 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/favorite-color"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/main.js"
    volumes:
      - .:/app/backend
    ports:
      - "3001:3001"
    links:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: favorite-color
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
